#!/usr/bin/perl
# -*- perl -*-

# Copyright (c) 2014
# Author: Jeff Weisberg <jaw @ solvemedia.com>
# Created: 2014-Mar-31 16:59 (EDT)
# Function: 


use lib '/home/adcopy/lib';
use lib '/home/nfs1/u/jaw/dev/mrquincy/lib';

use AC::MrQuincy::Client;
use AC::MrQuincy::Submit::Parse;
use AC::MrQuincy::Submit::Compile;

use AC::Protocol;
use AC::Dumper;
use AC::Misc;
use JSON;
use Socket;

require 'AC/MrQuincy/proto/std_reply.pl';
require 'AC/MrQuincy/proto/mrmagoo.pl';

use strict;

my $mrm =  AC::MrQuincy::Client->new( 'ruby', file => 'eg/mrjob');
my $j   =  $mrm->compile(
    {foo => 123, bar => 456},
    perlbin         => '/usr/bin/perl',
    libdir          => '/home/nfs1/u/jaw/dev/mrquincy/lib',
    runinit         => 0,
    dumpsrc         => 0,
    no_syntax_check => 1,
);


print STDERR dumper($j);



